name: Предложение
description: Предложить улучшение
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу решает улучшение
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Как должно работать
    validations:
      required: true
