"""Centralized external format and Telegram Bot API limits."""

from __future__ import annotations

MIB = 1024 * 1024

TELEGRAM_CUSTOM_EMOJI_SET_MAX = 200
TELEGRAM_REGULAR_STICKER_SET_MAX = 120
TELEGRAM_CREATE_INITIAL_MAX = 50
TELEGRAM_TGS_MAX_BYTES = 64 * 1024
TELEGRAM_WEBM_MAX_BYTES = 256 * 1024
TELEGRAM_STATIC_STICKER_MAX_BYTES = 512 * 1024
TELEGRAM_VIDEO_MAX_DURATION_SECONDS = 3.0
# Telegram may reject a WEBM whose container rounds to just over 3 seconds even
# when FFmpeg reports 00:00:03.00. Generated assets are trimmed with a margin.
TELEGRAM_VIDEO_SAFE_DURATION_SECONDS = 2.9
TELEGRAM_VIDEO_MAX_FPS = 30
TELEGRAM_REGULAR_STICKER_SIDE = 512
TELEGRAM_CUSTOM_EMOJI_SIDE = 100
TELEGRAM_TGS_CANVAS_SIDE = 512
TELEGRAM_SHORT_NAME_MAX = 64
TELEGRAM_PACK_TITLE_MAX = 64

SUPPORTED_EXTENSIONS = frozenset({".tgs", ".webm", ".webp", ".png"})
IGNORED_ARCHIVE_NAMES = frozenset({".ds_store", "thumbs.db", "__macosx"})
DEFAULT_ASSOCIATED_EMOJI = "🎨"
